pipeline {
    agent any

    environment {
        IMAGE_NAME = "localhost:5001/flask-homelab"
        TAG = "v1"
        KUBECONFIG = "/root/.kube/config"
    }

    stages {

        stage('Checkout') {
            steps {
                git 'https://github.com/kobyobeng/devops-homelab.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME:$TAG ./app'
            }
        }

        stage('Push to Local Registry') {
            steps {
                sh 'docker push $IMAGE_NAME:$TAG'
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh 'kubectl apply -f k8s/'
            }
        }

        stage('Verify Deployment') {
            steps {
                sh 'kubectl get pods -n devops-homelab'
            }
        }
    }
}
