pipeline {
    agent any

    environment {
        REGISTRY = "localhost:5001"
        IMAGE = "flask-homelab"
        NAMESPACE = "devops-homelab"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                url: 'https://github.com/kobyobeng/devops-homelab.git'
            }
        }

        stage('Set Build Tag') {
            steps {
                script {
                    env.TAG = sh(
                        script: 'git rev-parse --short HEAD',
                        returnStdout: true
                    ).trim()
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                sh """
                docker build -t $REGISTRY/$IMAGE:$TAG ./app
                """
            }
        }

        stage('Push Image') {
            steps {
                sh """
                docker push $REGISTRY/$IMAGE:$TAG
                """
            }
        }

        stage('Deploy') {
            steps {
                sh """
                kubectl set image deployment/flask-homelab \
                flask-homelab=$REGISTRY/$IMAGE:$TAG \
                -n $NAMESPACE
                """
            }
        }

        stage('Verify Rollout') {
            steps {
                sh """
                kubectl rollout status deployment/flask-homelab \
                -n $NAMESPACE \
                --timeout=120s
                """
            }
        }

        stage('Health Check') {
            steps {
                sh """
                kubectl get pods -n $NAMESPACE
                """
            }
        }
    }

    post {
        success {
            echo 'Deployment Successful 🚀'
        }

        failure {
            echo 'Deployment Failed ❌'
        }
    }
}
